# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18b90e8bf0a2cafe9b490e5a4436c8cc02069e95432433b30b2effe3bd26d7cb742aa458b4f35bae16dc7ff6750206201aa47d25b366d3f759acea19119d887d

test:
  secret_key_base: 02dfdd7b317339b82f7354cc5376c6ae73e537bd179a5c3b17bf999e598b675f717a97091f9a2d61f354c2360290ffd8bd7817a36d9d9f0772675d9136ea17bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
